server.port: 8082

spring:
  security:
    user:
      password: test
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_security?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: JavaForever
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:

      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  reactor:
    debug-agent:
      enabled:

springdoc:
  api-docs:
    path: /api-docs